# Generated by Django 4.2.17 on 2026-04-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_ordered_by_alter_order_table_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0021_alter_maincategory_image_alter_restaurant_logo'),
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwastelog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='foodwastelog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='foodwastelog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_logs', to='restaurant.product'),
        ),
        migrations.AlterField(
            model_name='foodwastelog',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercostbreakdown',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cost_breakdown', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='productcostsettings',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cost_settings', to='restaurant.product'),
        ),
        migrations.AlterField(
            model_name='wastereportsummary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_summaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
