# Generated by Django 4.2.17 on 2026-04-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_billrequest_requested_by_and_more'),
        ('waste_management', '0002_alter_foodwastelog_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwastelog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='orders.orderitem'),
        ),
    ]
