# Generated by Django 4.2.30 on 2026-06-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0023_alter_event_owner"),
        ("waste_management", "0004_wastereportsummary_all_reasons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodwastelog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waste_logs",
                to="restaurant.product",
            ),
        ),
        migrations.AlterField(
            model_name="productcostsettings",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_settings",
                to="restaurant.product",
            ),
        ),
    ]
