# Generated by Django 4.2.17 on 2026-04-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_add_order_indexes'),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitempayment',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitempayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_payments', to='cashier.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voidtransaction',
            name='original_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.payment'),
        ),
        migrations.AlterField(
            model_name='voidtransaction',
            name='voided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
