# Generated by Django 4.2.17 on 2026-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_protect_payment_financial_records'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='cashier_pay_order_i_886776_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['processed_by'], name='cashier_pay_process_6e9f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='cashier_pay_created_71abdd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_voided'], name='cashier_pay_is_void_2667d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='cashier_pay_payment_9b0ee5_idx'),
        ),
    ]
