# Generated by Django 5.0.14 on 2025-11-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_restaurantsubscription_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_print_bot',
            field=models.BooleanField(default=True, help_text='Automatically print Bar Order Tickets when order is placed'),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_print_kot',
            field=models.BooleanField(default=True, help_text='Automatically print Kitchen Order Tickets when order is placed'),
        ),
    ]
