# Generated by Django 5.0.14 on 2025-11-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_auto_print_bot_user_auto_print_kot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bar_printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name for Bar Order Tickets (leave blank for auto-detect)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kitchen_printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name for Kitchen Order Tickets (leave blank for auto-detect)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receipt_printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name for Payment Receipts (leave blank for auto-detect)', max_length=200, null=True),
        ),
    ]
