# Generated by Django 5.0.14 on 2025-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_bar_printer_name_user_kitchen_printer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('main_owner', 'Main Owner'), ('branch_owner', 'Branch Owner'), ('owner', 'Owner'), ('customer_care', 'Customer Care'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('cashier', 'Cashier'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
