# Generated by Django 5.0.14 on 2025-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_hierarchical_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlog',
            name='action',
            field=models.CharField(choices=[('created', 'Subscription Created'), ('auto_created', 'Auto-Created for Existing Restaurant'), ('extended', 'Subscription Extended'), ('blocked', 'Restaurant Blocked'), ('unblocked', 'Restaurant Unblocked'), ('expired', 'Subscription Expired'), ('renewed', 'Subscription Renewed'), ('cancelled', 'Subscription Cancelled'), ('plan_changed', 'Plan Changed')], max_length=20),
        ),
    ]
