# Generated by Django 5.0.14 on 2025-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_subscriptionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'USD - US Dollar ($)'), ('EUR', 'EUR - Euro (€)'), ('GBP', 'GBP - British Pound (£)'), ('KES', 'KES - Kenyan Shilling (KSh)'), ('TZS', 'TZS - Tanzanian Shilling (TSh)'), ('UGX', 'UGX - Ugandan Shilling (USh)'), ('RWF', 'RWF - Rwandan Franc (RF)'), ('ZAR', 'ZAR - South African Rand (R)'), ('NGN', 'NGN - Nigerian Naira (₦)'), ('GHS', 'GHS - Ghanaian Cedi (GH₵)'), ('INR', 'INR - Indian Rupee (₹)'), ('AED', 'AED - UAE Dirham (AED)'), ('SAR', 'SAR - Saudi Riyal (SAR)'), ('CNY', 'CNY - Chinese Yuan (¥)'), ('JPY', 'JPY - Japanese Yen (¥)')], default='USD', help_text='Currency for displaying prices', max_length=3),
        ),
    ]
