# Generated by Django 5.0.14 on 2025-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('main_owner', 'Main Owner'), ('branch_owner', 'Branch Owner'), ('owner', 'Owner'), ('customer_care', 'Customer Care'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('buffet', 'Buffet'), ('service', 'Service'), ('cashier', 'Cashier'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
