# Generated by Django 5.0.14 on 2025-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_print_buffet',
            field=models.BooleanField(default=True, help_text='Automatically print Buffet Order Tickets when order is placed'),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_print_service',
            field=models.BooleanField(default=True, help_text='Automatically print Service Order Tickets when order is placed'),
        ),
        migrations.AddField(
            model_name='user',
            name='buffet_printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name for Buffet Order Tickets (leave blank for auto-detect)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='service_printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name for Service Order Tickets (leave blank for auto-detect)', max_length=200, null=True),
        ),
    ]
