# Generated by Django 5.0.1 on 2025-12-29 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_user_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('permission_denied', 'Permission Denied'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('action_create', 'Record Created'), ('action_update', 'Record Updated'), ('action_delete', 'Record Deleted'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('order_status_change', 'Order Status Changed'), ('payment_processed', 'Payment Processed'), ('payment_voided', 'Payment Voided'), ('refund_issued', 'Refund Issued'), ('staff_created', 'Staff Account Created'), ('staff_updated', 'Staff Account Updated'), ('staff_deactivated', 'Staff Account Deactivated'), ('menu_updated', 'Menu Updated'), ('table_updated', 'Table Configuration Updated'), ('settings_changed', 'Settings Changed'), ('session_hijack_attempt', 'Session Hijack Attempt'), ('suspicious_activity', 'Suspicious Activity Detected'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('other', 'Other Event')], db_index=True, max_length=30)),
                ('username', models.CharField(help_text='Username at time of event', max_length=150)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='accounts_au_event_t_03bfa1_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_au_ip_addr_394cd9_idx'), models.Index(fields=['target_model', 'target_id'], name='accounts_au_target__e8b882_idx')],
            },
        ),
    ]
