# Generated by Django 4.2.17 on 2026-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('main_owner', 'Main Owner'), ('branch_owner', 'Branch Owner'), ('owner', 'Owner'), ('manager', 'Manager'), ('customer_care', 'Customer Care'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('buffet', 'Buffet'), ('service', 'Service'), ('cashier', 'Cashier'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
