# Generated by Django 4.2.17 on 2026-04-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='restaurant_owner',
            field=models.OneToOneField(limit_choices_to={'role__name': 'owner'}, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='accounts.restaurantsubscription'),
        ),
    ]
