# Generated by Django 4.2.17 on 2026-04-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_restaurantsubscription_restaurant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='restaurant_owner',
            field=models.OneToOneField(limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
