# Generated by Django 4.2.17 on 2026-04-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_subscription_owner_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
