# Generated by Django 4.2.30 on 2026-06-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_expo_push_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("main_owner", "Main Owner"),
                    ("branch_owner", "Branch Owner"),
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("customer_care", "Customer Care"),
                    ("kitchen", "Kitchen"),
                    ("bar", "Bar"),
                    ("buffet", "Buffet"),
                    ("service", "Service"),
                    ("cashier", "Cashier"),
                    ("delivery_rider", "Delivery Rider"),
                    ("customer", "Customer"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
