# Generated by Django 4.2.30 on 2026-05-31 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("produce", "Fresh Produce"),
                            ("meat", "Meat & Poultry"),
                            ("seafood", "Seafood"),
                            ("dairy", "Dairy & Eggs"),
                            ("dry_goods", "Dry Goods & Grains"),
                            ("beverages", "Beverages"),
                            ("spices", "Spices & Condiments"),
                            ("packaging", "Packaging & Supplies"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pieces", "Pieces"),
                            ("kg", "Kilograms (kg)"),
                            ("g", "Grams (g)"),
                            ("liter", "Liters (L)"),
                            ("ml", "Milliliters (ml)"),
                            ("bottles", "Bottles"),
                            ("boxes", "Boxes"),
                            ("bags", "Bags"),
                            ("cans", "Cans"),
                            ("other", "Other"),
                        ],
                        default="pieces",
                        max_length=20,
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Alert when current stock falls at or below this value",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Restaurant owner who owns this inventory item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening Stock"),
                            ("received", "Stock Received"),
                            ("closing", "Closing Count"),
                            ("adjustment", "Manual Adjustment"),
                            ("used", "Used / Consumed"),
                            ("waste", "Waste / Spoilage"),
                            ("returned", "Returned to Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive to add stock, negative to remove stock",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
