# Generated by Django 4.2.30 on 2026-06-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Produce, Meat, Beverages — enter your own",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                default="",
                help_text="e.g. kg, pieces, bottles — enter your own",
                max_length=100,
            ),
        ),
    ]
