# Generated by Django 4.2.30 on 2026-06-01 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_add_category_unit_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per unit of this item (optional, used for cost tracking in reports)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
