# Generated by Django 4.2.30 on 2026-06-01 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_unit_price_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrecord",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per unit at time of this record — used for budget/spend tracking",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
