# Generated by Django 4.2.17 on 2026-04-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0021_alter_maincategory_image_alter_restaurant_logo'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierperformance',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productsalesdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.product'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.maincategory'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.subcategory'),
        ),
    ]
