# Generated by Django 4.2.30 on 2026-06-09 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0023_alter_event_owner"),
        ("reports", "0002_alter_cashierperformance_cashier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsalesdetail",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.product",
            ),
        ),
    ]
