# Generated by Django 5.0.14 on 2025-11-12 11:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_product_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Restaurant or branch name (e.g., 'Pizza Palace - Downtown')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this restaurant/branch')),
                ('address', models.TextField(help_text='Full address of this restaurant/branch')),
                ('is_main_restaurant', models.BooleanField(default=False, help_text='True if this is the main restaurant (not a branch)')),
                ('qr_code', models.CharField(help_text='Unique QR code for customer access', max_length=50, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Tax rate as decimal (e.g., 0.0800 for 8%)', max_digits=5)),
                ('auto_print_kot', models.BooleanField(default=True, help_text='Auto-print Kitchen Order Tickets')),
                ('auto_print_bot', models.BooleanField(default=True, help_text='Auto-print Bar Order Tickets')),
                ('kitchen_printer_name', models.CharField(blank=True, help_text='Kitchen printer name (blank for auto-detect)', max_length=200, null=True)),
                ('bar_printer_name', models.CharField(blank=True, help_text='Bar printer name (blank for auto-detect)', max_length=200, null=True)),
                ('receipt_printer_name', models.CharField(blank=True, help_text='Receipt printer name (blank for auto-detect)', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this restaurant/branch is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_owner', models.ForeignKey(blank=True, help_text='Branch manager (can be same as main_owner for main restaurant)', limit_choices_to={'role__name__in': ['main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_restaurant', to=settings.AUTH_USER_MODEL)),
                ('main_owner', models.ForeignKey(help_text='Main owner who controls this restaurant and its branches', limit_choices_to={'role__name': 'main_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
                ('parent_restaurant', models.ForeignKey(blank=True, help_text='Parent restaurant (only for branches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['main_owner__username', 'is_main_restaurant', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('is_main_restaurant', True), models.Q(('parent_restaurant', None), _negated=True), _negated=True), name='main_restaurant_no_parent'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('is_main_restaurant', False), ('parent_restaurant', None), _negated=True), name='branch_must_have_parent'),
        ),
    ]
