# Generated by Django 5.0.14 on 2025-11-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_create_restaurant_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maincategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant/branch this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='tableinfo',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant/branch this table belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='maincategory',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_category_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='maincategory',
            constraint=models.UniqueConstraint(condition=models.Q(('restaurant__isnull', False)), fields=('restaurant', 'name'), name='unique_category_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='maincategory',
            constraint=models.CheckConstraint(check=models.Q(('owner__isnull', False), ('restaurant__isnull', False), _connector='OR'), name='category_must_have_owner_or_restaurant'),
        ),
    ]
