# Generated by Django 5.0.14 on 2025-11-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_add_restaurant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subscription_plan',
            field=models.CharField(choices=[('SINGLE', 'Single Restaurant'), ('PRO', 'Pro Plan (Multi-Branch)')], default='SINGLE', help_text='Subscription plan that determines branch creation abilities', max_length=10),
        ),
    ]
