# Generated by Django 5.0.14 on 2025-11-19 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_add_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableinfo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='happyhourpromotion',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='happy_hour_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tableinfo',
            constraint=models.CheckConstraint(check=models.Q(('owner__isnull', False), ('restaurant__isnull', False), _connector='OR'), name='table_must_have_owner_or_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='tableinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'tbl_no'), name='unique_table_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tableinfo',
            constraint=models.UniqueConstraint(condition=models.Q(('restaurant__isnull', False)), fields=('restaurant', 'tbl_no'), name='unique_table_per_restaurant'),
        ),
    ]
