# Generated by Django 5.0.14 on 2025-12-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_update_promotion_owner_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='branch_owner',
            field=models.ForeignKey(blank=True, help_text='Branch manager (can be same as main_owner for main restaurant)', limit_choices_to={'role__name__in': ['main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='main_owner',
            field=models.ForeignKey(help_text='Main owner who controls this restaurant and its branches', limit_choices_to={'role__name': 'main_owner'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='parent_restaurant',
            field=models.ForeignKey(blank=True, help_text='Parent restaurant (only for branches)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='restaurant.restaurant'),
        ),
    ]
