# Generated by Django 5.0.14 on 2025-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_add_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='auto_print_buffet',
            field=models.BooleanField(default=True, help_text='Auto-print Buffet Order Tickets'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='auto_print_service',
            field=models.BooleanField(default=True, help_text='Auto-print Service Order Tickets'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='buffet_printer_name',
            field=models.CharField(blank=True, help_text='Buffet printer name (blank for auto-detect)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_printer_name',
            field=models.CharField(blank=True, help_text='Service printer name (blank for auto-detect)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='station',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('buffet', 'Buffet'), ('service', 'Service')], default='kitchen', help_text='Assign to kitchen, bar, buffet, or service station', max_length=20),
        ),
    ]
