# Generated by Django 5.0.1 on 2025-12-28 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_restaurant_auto_print_buffet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='capacity',
            field=models.IntegerField(default=4, help_text='Maximum seating capacity for this table', validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1.'), django.core.validators.MaxValueValidator(50, message='Capacity cannot exceed 50.')]),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='tbl_no',
            field=models.CharField(help_text='Unique table identifier (e.g., T1, A-01, VIP-1)', max_length=10, validators=[django.core.validators.RegexValidator(message='Table number can only contain letters, numbers, hyphens, and underscores.', regex='^[A-Za-z0-9\\-_]+$')]),
        ),
    ]
