# Generated by Django 5.0.1 on 2025-12-28 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_add_tableinfo_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['is_active'], name='restaurant__is_acti_479a07_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['owner'], name='restaurant__owner_i_eb90d3_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_310f95_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='restaurant__is_avai_807614_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['main_category'], name='restaurant__main_ca_d29b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['station'], name='restaurant__station_66fb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tableinfo',
            index=models.Index(fields=['is_available'], name='restaurant__is_avai_f12b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='tableinfo',
            index=models.Index(fields=['owner'], name='restaurant__owner_i_b6bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='tableinfo',
            index=models.Index(fields=['restaurant'], name='restaurant__restaur_c726f5_idx'),
        ),
    ]
