# Generated by Django 5.0.14 on 2026-02-02 09:12

from django.db import migrations, models
import uuid


def generate_menu_qr_codes(apps, schema_editor):
    """Generate menu QR codes for existing restaurants"""
    Restaurant = apps.get_model('restaurant', 'Restaurant')
    
    for restaurant in Restaurant.objects.all():
        if not restaurant.menu_qr_code:
            # Generate unique menu QR code
            restaurant.menu_qr_code = f"MENU-{uuid.uuid4().hex[:12].upper()}"
            restaurant.save()


def reverse_generate_menu_qr_codes(apps, schema_editor):
    """Reverse migration - clear menu QR codes"""
    Restaurant = apps.get_model('restaurant', 'Restaurant')
    Restaurant.objects.all().update(menu_qr_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_qr_code',
            field=models.CharField(blank=True, help_text='Unique QR code for view-only menu (no login, no ordering)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code',
            field=models.CharField(help_text='Unique QR code for customer ordering (login required)', max_length=50, unique=True),
        ),
        migrations.RunPython(generate_menu_qr_codes, reverse_generate_menu_qr_codes),
    ]
