# Generated by Django 5.0.14 on 2026-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_add_menu_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant logo (displayed on menu QR view)', null=True, upload_to='restaurant_logos/'),
        ),
    ]
