# Generated by Django 5.0.14 on 2026-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='wifi_password',
            field=models.CharField(blank=True, help_text='WiFi password for customers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wifi_ssid',
            field=models.CharField(blank=True, help_text='WiFi network name (SSID) for customers', max_length=100, null=True),
        ),
    ]
