# Generated by Django 5.0.14 on 2026-02-05 09:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_add_wifi_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Event title (e.g., 'Smith Wedding Reception')", max_length=200)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('anniversary', 'Anniversary'), ('graduation', 'Graduation'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('cocktail', 'Cocktail Party'), ('buffet', 'Buffet Event'), ('private_dining', 'Private Dining'), ('holiday', 'Holiday Event'), ('other', 'Other')], default='other', help_text='Type of event', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the event')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('start_time', models.TimeField(help_text='Event start time')),
                ('end_time', models.TimeField(blank=True, help_text='Event end time (optional)', null=True)),
                ('total_pax', models.PositiveIntegerField(help_text='Total number of guests/persons')),
                ('price_per_pax', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('contact_name', models.CharField(help_text='Client/organizer name', max_length=100)),
                ('contact_phone', models.CharField(help_text='Client phone number', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Client email address (optional)', max_length=254)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit amount received', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=10)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', help_text='Current status of the event', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit Paid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', help_text='Payment status', max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Dietary requirements, setup instructions, etc.')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Restaurant owner managing this event', limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', '-start_time'],
                'indexes': [models.Index(fields=['event_date'], name='restaurant__event_d_0e9a76_idx'), models.Index(fields=['status'], name='restaurant__status_32058b_idx'), models.Index(fields=['owner', 'event_date'], name='restaurant__owner_i_133d3b_idx')],
            },
        ),
    ]
