# Generated by Django 4.2.17 on 2026-04-07 04:00

from django.db import migrations, models
import restaurant.models
import restaurant.models_restaurant


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_add_event_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[restaurant.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant logo (displayed on menu QR view)', null=True, upload_to='restaurant_logos/', validators=[restaurant.models_restaurant.validate_restaurant_image]),
        ),
    ]
