# Generated by Django 4.2.17 on 2026-04-07 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0021_alter_maincategory_image_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhourpromotion',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, on_delete=django.db.models.deletion.PROTECT, related_name='happy_hour_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant/branch this category belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_categories', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='restaurant.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='restaurant.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='restaurant.maincategory'),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Restaurant/branch this table belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='restaurant.restaurant'),
        ),
    ]
