# Generated by Django 4.2.17 on 2026-04-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0022_alter_happyhourpromotion_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(help_text='Restaurant owner managing this event', limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
