# Generated by Django 5.0.14 on 2025-11-10 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
        ('orders', '0003_billrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('kot', 'Kitchen Order Ticket'), ('bot', 'Bar Order Ticket'), ('receipt', 'Payment Receipt')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('content', models.TextField(help_text='Print content (plain text)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('printed_by_client', models.CharField(blank=True, help_text='Client identifier', max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='cashier.payment')),
                ('restaurant', models.ForeignKey(help_text='Restaurant owner whose printer should print this', on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status', '-created_at'], name='orders_prin_restaur_cd1328_idx'), models.Index(fields=['status', '-created_at'], name='orders_prin_status_d517d0_idx')],
            },
        ),
    ]
