# Generated by Django 5.0.14 on 2025-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='printer_name',
            field=models.CharField(blank=True, help_text='Specific printer name to use (blank for auto-detect)', max_length=255, null=True),
        ),
    ]
