# Generated by Django 4.2.17 on 2026-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_order_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table_info', 'payment_status'], name='orders_orde_table_i_91cbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ordered_by'], name='orders_orde_ordered_3ea3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='orders_orde_created_49d91d_idx'),
        ),
    ]
