# Generated by Django 4.2.17 on 2026-04-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_add_performance_indexes'),
        ('orders', '0008_alter_order_ordered_by_alter_order_table_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='cashier.payment'),
        ),
    ]
