# Generated by Django 4.2.17 on 2026-04-07 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_alter_event_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_alter_printjob_order_alter_printjob_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billrequest',
            name='table_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_requests', to='restaurant.tableinfo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.product'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='restaurant',
            field=models.ForeignKey(help_text='Restaurant owner whose printer should print this', on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
