# Generated by Django 4.2.17 on 2026-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_billrequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billrequest',
            index=models.Index(fields=['status'], name='orders_bill_status_9aaca0_idx'),
        ),
        migrations.AddIndex(
            model_name='billrequest',
            index=models.Index(fields=['created_at'], name='orders_bill_created_c0c8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='billrequest',
            index=models.Index(fields=['table_info', 'status'], name='orders_bill_table_i_5fb88f_idx'),
        ),
    ]
