# Generated by Django 4.2.30 on 2026-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_billrequest_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("kot", "Kitchen Order Ticket"),
                    ("bot", "Bar Order Ticket"),
                    ("receipt", "Payment Receipt"),
                    ("bill", "Bill / Pre-Payment Receipt"),
                    ("buffet", "Buffet Order Ticket"),
                    ("service", "Service Order Ticket"),
                ],
                max_length=20,
            ),
        ),
    ]
