# Generated by Django 4.2.30 on 2026-06-25 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0016_add_delivery_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrider",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__name__in": ["owner", "main_owner", "branch_owner"]
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_riders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
