# Generated by Django 4.2.30 on 2026-08-29 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_order_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrider',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['owner', 'main_owner', 'branch_owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_riders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
